### ISSUE TITLE
Documentation error: "index" function example

### ISSUE THREAD

**Issue by fuxoft** [kosh04/newlisp#3]
In the documentation of the "index" function, the last example line says:
`(select '(1 10 3 6 4 5 11) '(1 3 6)) → (1 3 6)`
This is wrong. The returned value is not (1 3 6) but (10 6 11).

**Comment by cryptorick** [comment]
Thanks for spotting that.  This repo isn't "upstream" for newLISP, so I reported it [here where the dev will see it and fix it](http://www.newlispfanclub.alh.net/forum/viewtopic.php?f=2&t=4765).

**Comment by fuxoft** [comment]
Thanks. I couldn't find the proper channel to report that...
